select
    CAST(id as INTEGER)
    , CAST(owner_id as INTEGER)
    , CAST(creation_date as TIMESTAMP) as created_at
    , CAST(count_visit as INTEGER)
    , CAST(rent_cost as BIGINT)
    , CAST(displayed as BOOLEAN)
    , CAST(notification as BOOLEAN)
    , CAST(validated as BOOLEAN)
    , CAST(type as VARCHAR)
    , CAST(furniture as VARCHAR)
    , CAST(charges_cost as FLOAT)
    , CAST(living_space as FLOAT)
    , CAST(energy_consumption as INTEGER)
    , CAST(co2emission as INTEGER)
    , CAST(validated_date as TIMESTAMP)
    , CAST(ademe_number as VARCHAR)
    , CAST(dpe_date as TIMESTAMP)
    , CAST(dpe_not_required as BOOLEAN)
from {{ source('dossierfacile', 'property') }}
