models:
  - name: staging_tenant_log
    description: "A starter dbt model to clean tenant_log table"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: tenant_id
        description: "The ID of the tenant associated with the log"
        data_tests:
          - not_null
      - name: operator_id
        description: "The ID of the operator who performed the action"
      - name: log_type
        description: "The type of log entry"
      - name: created_at
        description: "The timestamp when the log entry was created"
        data_tests:
          - not_null
      - name: migrate
        description: "Flag indicating if the log entry has been migrated"
  - name: staging_tenant
    description: "A dbt model to clean and transform tenant data"
    columns:
      - name: id
        description: "The primary key for the tenant table"
        data_tests:
          - unique
          - not_null
      - name: tenant_type
        description: "The type of tenant"
        data_tests:
          - not_null
      - name: status
        description: "The current status of the tenant"
        data_tests:
          - not_null
      - name: application_id
        description: "The ID of the application (apartment_sharing in code)"
      - name: zip_code
        description: "The zip code of the tenant's address"
      - name: honor_declaration
        description: "Flag indicating if the tenant has made an honor declaration"
      - name: last_updated_at
        description: "The timestamp of the last update to the tenant record"
      - name: tenant_comment
        description: "The tenant's comment for the property owner"
      - name: last_operation_at
        description: "The timestamp of the last operation performed on the tenant record"
      - name: deletion_warnings
        description: "The number of warnings before deletion"
      - name: tenant_abroad
        description: "Flag indicating if the tenant is abroad"
  - name: staging_document_denied_options
    description: "A dbt model to clean the document_denied_options table"
    columns:
      - name: id
        description: "The primary key for the denied options table"
        data_tests:
          - unique
          - not_null
      - name: message_value
        description: "The primary key for the denied reasons"
      - name: document_sub_category
        description: "The sub category of the document"
      - name: document_user_type
        description: "The type of user associated to the denied option"
      - name: code
        description: "The associated code to the denied option"
  - name: staging_document_denied_reasons
    description: "A dbt model that cleans and transforms document denied reasons data from the source table"
    columns:
      - name: id
        description: "The ID of the denied reason record"
        data_tests:
          - not_null
      - name: denied_option_id
        description: "The ID of the denial reason option"
        data_tests:
          - not_null
      - name: denied_option_value
        description: "The value of the denial reason option"
        data_tests:
          - not_null
      - name: operator_comment
        description: "Any comments made by the operator regarding the denial"
      - name: document_id
        description: "The ID of the document that was denied"
        data_tests:
          - not_null
      - name: created_at
        description: "Timestamp when the document was denied"
        data_tests:
          - not_null
      - name: document_category
        description: "The category of the denied document"
      - name: document_sub_category
        description: "The sub-category of the denied document"
      - name: document_category_step
        description: "The step in the document category process"
      - name: document_tenant_type
        description: "Indicates whether the document belongs to a TENANT or GUARANTOR"
