models:
  - name: staging_tenant_log
    description: "A starter dbt model to clean tenant_log table"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: tenant_id
        description: "The ID of the tenant associated with the log"
        data_tests:
          - not_null
      - name: operator_id
        description: "The ID of the operator who performed the action"
      - name: log_type
        description: "The type of log entry"
      - name: created_at
        description: "The timestamp when the log entry was created"
        data_tests:
          - not_null
      - name: migrate
        description: "Flag indicating if the log entry has been migrated"
  - name: staging_owner_log
    description: "A starter dbt model to clean owner_log table"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: owner_id
        description: "The ID of the owner associated with the log"
        data_tests:
          - not_null
      - name: created_at
        description: "The timestamp when the log entry was created"
        data_tests:
          - not_null
      - name: log_type
        description: "The type of log entry"
        data_tests:
          - not_null
  - name: staging_owner_log_json
    description: "A starter dbt model to extract and clean the json_profile in owner_log table"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: owner_id
        description: "The ID of the owner associated with the log"
        data_tests:
          - not_null
      - name: owner_deleted_at
        description: "The timestamp of the deletion of the owner account (when the json is created)"
        data_tests:
          - not_null
      - name: log_type
        description: "The type of log entry"
        data_tests:
          - not_null
      - name: owner_created_at
        description: "The timestamp when the owner account was created"
        data_tests:
          - not_null

  - name: staging_tenant
    description: "A dbt model to clean and transform tenant data"
    columns:
      - name: id
        description: "The primary key for the tenant table"
        data_tests:
          - unique
          - not_null
      - name: tenant_type
        description: "The type of tenant"
      - name: apartment_sharing_id
        description: "The ID of the apartment sharing group"
      - name: zip_code
        description: "The zip code of the tenant's address"
      - name: honor_declaration
        description: "Flag indicating if the tenant has made an honor declaration"
      - name: last_updated_at
        description: "The timestamp of the last update to the tenant record"
      - name: tenant_comment
        description: "The tenant's comment for the property owner"
      - name: status
        description: "The current status of the tenant"
      - name: last_operation_at
        description: "The timestamp of the last operation performed on the tenant record"
      - name: deletion_warnings
        description: "The number of warnings before deletion"
      - name: operator_comment
        description: "Comments made by the operator"
      - name: tenant_abroad
        description: "Flag indicating if the tenant is abroad"
