name: Pipeline CI Data
on: pull_request

env:
  DBT_PROFILES_DIR: ./.github/
  POSTGRES_PASSWORD: "${{ secrets.DBT_POSTGRES_PASSWORD_TEST }}"

jobs:

  run-ci-pipeline:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.1
        ports:
        # will assign a random free host port
          - 5432/tcp
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"

      - name: Install dbt
        run: pip install dbt-postgres==1.9.0

      - name: Instal dbt deps
        run: dbt deps

      - name: Install SQLFluff
        run: pip install sqlfluff==3.3.0

      - name: Install SQLFluff dbt templater
        run: pip install sqlfluff-templater-dbt==3.3.0
        
      - name: Lint with SQLFluff
        run: sqlfluff lint --dialect postgres

      - name: Run dbt tests
        run: dbt build