sources:
  - name: dossierfacile
    database: dossierfacile
    schema: public
    loader: airflow
    freshness:
      warn_after: { count: 28, period: hour }
      error_after: { count: 56, period: hour }
    tables:
      - name: tenant_log
        columns: 
          - name: id 
            data_tests:
              - unique 
      - name: tenant
        columns:
          - name: id
            data_tests:
              - unique
      - name: user_account
        columns:
          - name: id
            data_tests:
              - unique
      - name: apartment_sharing
        columns:
          - name: id
            data_tests:
              - unique
      - name: document
        columns:
          - name: id
            data_tests:
              - unique
      - name: property
        columns:
          - name: id
            data_tests:
              - unique
  - name: dbt_dev
    database: dossierfacile
    schema: dbt_dev
    tables:
      - name: staging_tenant_log
      - name: staging_tenant
      - name: staging_user_account
