sources:
  - name: dossierfacile
    schema: public
    loader: airflow
    freshness:
      warn_after: { count: 28, period: hour }
      error_after: { count: 56, period: hour }
    tables:
      - name: tenant_log
        columns: 
          - name: id 
            data_tests:
              - unique 
      - name: tenant
        columns:
          - name: id
            data_tests:
              - unique
      - name: user_account
        columns:
          - name: id
            data_tests:
              - unique
      - name: apartment_sharing
        columns:
          - name: id
            data_tests:
              - unique
      - name: document
        columns:
          - name: id
            data_tests:
              - unique
      - name: document_denied_reasons
        columns:
          - name: id
            data_tests:
              - unique
      - name: document_denied_options
        columns:
          - name: id
            data_tests:
              - unique
      - name: property
        columns:
          - name: id
            data_tests:
              - unique
      - name: property_log
        columns:
          - name: id
            data_tests:
              - unique
      - name: owner_log
        columns:
          - name: id
            data_tests:
              - unique
      - name: user_api
        columns:
          - name: id
            data_tests:
              - unique
      - name: tenant_userapi
