sources:
  - name: dossierfacile
    schema: public
    loader: airflow
    tables:
      - name: tenant_log
        loaded_at_field: creation_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: tenant
        loaded_at_field: last_update_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: user_account
        loaded_at_field: creation_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: apartment_sharing
        loaded_at_field: last_update_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: apartment_sharing_link
        loaded_at_field: creation_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: link_log
        loaded_at_field: creation_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: document
        loaded_at_field: creation_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: document_denied_reasons
        loaded_at_field: creation_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: document_denied_options
        columns:
          - name: id
            data_tests:
              - unique
      - name: document_analysis_report
        columns:
          - name: id
            data_tests:
              - unique
      - name: property
        columns:
          - name: id
            data_tests:
              - unique
      - name: property_log
        loaded_at_field: creation_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: owner_log
        loaded_at_field: creation_date
        columns:
          - name: id
            data_tests:
              - unique
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: user_api
        columns:
          - name: id
            data_tests:
              - unique
      - name: tenant_userapi
        loaded_at_field: access_granted_date
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: user_operator
        columns:
          - name: id
            data_tests:
              - unique
          - name: created_at
          - name: email
            data_tests:
              - not_null
          - name: first_name
          - name: last_name
      - name: operator_log
        description: "Log of operator actions on tenant applications"
        loaded_at_field: creation_date
        columns:
          - name: id
            data_tests:
              - unique
          - name: tenant_id
          - name: operator_id
          - name: tenant_status
          - name: action_type
          - name: creation_date
          - name: processed_documents
          - name: time_spent
        config:
          freshness:
            warn_after: {count: 28, period: hour}
            error_after: {count: 56, period: hour}
      - name: guarantor
        description: "Guarantor table"
        columns:
          - name: id
            data_tests:
              - unique
          - name: tenant_id
            data_tests:
              - not_null
          - name: type_guarantor